// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agent_service.proto

package io.sandstorm.exchange.api;

public final class AgentServiceProto {
  private AgentServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023agent_service.proto\032\016messages.proto2\210\001" +
      "\n\014AgentService\022\'\n\nPrepareFor\022\013.TestJobMs" +
      "g\032\n.ResultMsg\"\000\022,\n\017StartTestEngine\022\013.Tes" +
      "tJobMsg\032\n.ResultMsg\"\000\022!\n\004Stop\022\013.TestJobM" +
      "sg\032\n.ResultMsg\"\000B0\n\031io.sandstorm.exchang" +
      "e.apiB\021AgentServiceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.sandstorm.exchange.api.msg.TestTaskProto.getDescriptor(),
        }, assigner);
    io.sandstorm.exchange.api.msg.TestTaskProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
