// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controller_service.proto

package io.sandstorm.exchange.api;

public final class ControllerServiceProto {
  private ControllerServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030controller_service.proto\032\016messages.pro" +
      "to2\217\002\n\021ControllerService\0226\n\024RegisterLoad" +
      "Injector\022\020.LoadInjectorMsg\032\n.ResultMsg\"\000" +
      "\0221\n\026OnPreparationSucceeded\022\t.JobIdMsg\032\n." +
      "ResultMsg\"\000\0225\n\023OnPreparationFailed\022\020.Res" +
      "ultNotifyMsg\032\n.ResultMsg\"\000\022)\n\016OnJobCompl" +
      "eted\022\t.JobIdMsg\032\n.ResultMsg\"\000\022-\n\013OnJobFa" +
      "iled\022\020.ResultNotifyMsg\032\n.ResultMsg\"\000B5\n\031" +
      "io.sandstorm.exchange.apiB\026ControllerSer" +
      "viceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.sandstorm.exchange.api.msg.TestTaskProto.getDescriptor(),
        }, assigner);
    io.sandstorm.exchange.api.msg.TestTaskProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
