// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package io.sandstorm.exchange.api.msg;

public interface DataSetMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DataSetMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string feeder_file_name = 1;</code>
   */
  java.lang.String getFeederFileName();
  /**
   * <code>string feeder_file_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getFeederFileNameBytes();

  /**
   * <code>repeated .DataChunkMsg chunks = 2;</code>
   */
  java.util.List<io.sandstorm.exchange.api.msg.DataChunkMsg> 
      getChunksList();
  /**
   * <code>repeated .DataChunkMsg chunks = 2;</code>
   */
  io.sandstorm.exchange.api.msg.DataChunkMsg getChunks(int index);
  /**
   * <code>repeated .DataChunkMsg chunks = 2;</code>
   */
  int getChunksCount();
  /**
   * <code>repeated .DataChunkMsg chunks = 2;</code>
   */
  java.util.List<? extends io.sandstorm.exchange.api.msg.DataChunkMsgOrBuilder> 
      getChunksOrBuilderList();
  /**
   * <code>repeated .DataChunkMsg chunks = 2;</code>
   */
  io.sandstorm.exchange.api.msg.DataChunkMsgOrBuilder getChunksOrBuilder(
      int index);
}
