// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package io.sandstorm.exchange.api.msg;

public interface LoadInjectorMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LoadInjectorMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string hostname = 1;</code>
   */
  java.lang.String getHostname();
  /**
   * <code>string hostname = 1;</code>
   */
  com.google.protobuf.ByteString
      getHostnameBytes();

  /**
   * <code>int32 port = 2;</code>
   */
  int getPort();

  /**
   * <code>string intranet_ip = 3;</code>
   */
  java.lang.String getIntranetIp();
  /**
   * <code>string intranet_ip = 3;</code>
   */
  com.google.protobuf.ByteString
      getIntranetIpBytes();

  /**
   * <code>string public_ip = 4;</code>
   */
  java.lang.String getPublicIp();
  /**
   * <code>string public_ip = 4;</code>
   */
  com.google.protobuf.ByteString
      getPublicIpBytes();
}
