// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package io.sandstorm.exchange.api.msg;

public interface LoadProfileMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LoadProfileMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 scn_repeat_times = 1;</code>
   */
  long getScnRepeatTimes();

  /**
   * <code>repeated .UserInjectStepMsg user_inject_steps = 2;</code>
   */
  java.util.List<io.sandstorm.exchange.api.msg.UserInjectStepMsg> 
      getUserInjectStepsList();
  /**
   * <code>repeated .UserInjectStepMsg user_inject_steps = 2;</code>
   */
  io.sandstorm.exchange.api.msg.UserInjectStepMsg getUserInjectSteps(int index);
  /**
   * <code>repeated .UserInjectStepMsg user_inject_steps = 2;</code>
   */
  int getUserInjectStepsCount();
  /**
   * <code>repeated .UserInjectStepMsg user_inject_steps = 2;</code>
   */
  java.util.List<? extends io.sandstorm.exchange.api.msg.UserInjectStepMsgOrBuilder> 
      getUserInjectStepsOrBuilderList();
  /**
   * <code>repeated .UserInjectStepMsg user_inject_steps = 2;</code>
   */
  io.sandstorm.exchange.api.msg.UserInjectStepMsgOrBuilder getUserInjectStepsOrBuilder(
      int index);

  /**
   * <code>repeated .RpsThrotStepMsg rps_throt_steps = 3;</code>
   */
  java.util.List<io.sandstorm.exchange.api.msg.RpsThrotStepMsg> 
      getRpsThrotStepsList();
  /**
   * <code>repeated .RpsThrotStepMsg rps_throt_steps = 3;</code>
   */
  io.sandstorm.exchange.api.msg.RpsThrotStepMsg getRpsThrotSteps(int index);
  /**
   * <code>repeated .RpsThrotStepMsg rps_throt_steps = 3;</code>
   */
  int getRpsThrotStepsCount();
  /**
   * <code>repeated .RpsThrotStepMsg rps_throt_steps = 3;</code>
   */
  java.util.List<? extends io.sandstorm.exchange.api.msg.RpsThrotStepMsgOrBuilder> 
      getRpsThrotStepsOrBuilderList();
  /**
   * <code>repeated .RpsThrotStepMsg rps_throt_steps = 3;</code>
   */
  io.sandstorm.exchange.api.msg.RpsThrotStepMsgOrBuilder getRpsThrotStepsOrBuilder(
      int index);
}
