// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package io.sandstorm.exchange.api.msg;

/**
 * Protobuf type {@code LoadProfileMsg}
 */
public  final class LoadProfileMsg extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:LoadProfileMsg)
    LoadProfileMsgOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LoadProfileMsg.newBuilder() to construct.
  private LoadProfileMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LoadProfileMsg() {
    scnRepeatTimes_ = 0L;
    userInjectSteps_ = java.util.Collections.emptyList();
    rpsThrotSteps_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LoadProfileMsg(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            scnRepeatTimes_ = input.readInt64();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              userInjectSteps_ = new java.util.ArrayList<io.sandstorm.exchange.api.msg.UserInjectStepMsg>();
              mutable_bitField0_ |= 0x00000002;
            }
            userInjectSteps_.add(
                input.readMessage(io.sandstorm.exchange.api.msg.UserInjectStepMsg.parser(), extensionRegistry));
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              rpsThrotSteps_ = new java.util.ArrayList<io.sandstorm.exchange.api.msg.RpsThrotStepMsg>();
              mutable_bitField0_ |= 0x00000004;
            }
            rpsThrotSteps_.add(
                input.readMessage(io.sandstorm.exchange.api.msg.RpsThrotStepMsg.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        userInjectSteps_ = java.util.Collections.unmodifiableList(userInjectSteps_);
      }
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        rpsThrotSteps_ = java.util.Collections.unmodifiableList(rpsThrotSteps_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.sandstorm.exchange.api.msg.TestTaskProto.internal_static_LoadProfileMsg_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.sandstorm.exchange.api.msg.TestTaskProto.internal_static_LoadProfileMsg_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.sandstorm.exchange.api.msg.LoadProfileMsg.class, io.sandstorm.exchange.api.msg.LoadProfileMsg.Builder.class);
  }

  private int bitField0_;
  public static final int SCN_REPEAT_TIMES_FIELD_NUMBER = 1;
  private long scnRepeatTimes_;
  /**
   * <code>int64 scn_repeat_times = 1;</code>
   */
  public long getScnRepeatTimes() {
    return scnRepeatTimes_;
  }

  public static final int USER_INJECT_STEPS_FIELD_NUMBER = 2;
  private java.util.List<io.sandstorm.exchange.api.msg.UserInjectStepMsg> userInjectSteps_;
  /**
   * <code>repeated .UserInjectStepMsg user_inject_steps = 2;</code>
   */
  public java.util.List<io.sandstorm.exchange.api.msg.UserInjectStepMsg> getUserInjectStepsList() {
    return userInjectSteps_;
  }
  /**
   * <code>repeated .UserInjectStepMsg user_inject_steps = 2;</code>
   */
  public java.util.List<? extends io.sandstorm.exchange.api.msg.UserInjectStepMsgOrBuilder> 
      getUserInjectStepsOrBuilderList() {
    return userInjectSteps_;
  }
  /**
   * <code>repeated .UserInjectStepMsg user_inject_steps = 2;</code>
   */
  public int getUserInjectStepsCount() {
    return userInjectSteps_.size();
  }
  /**
   * <code>repeated .UserInjectStepMsg user_inject_steps = 2;</code>
   */
  public io.sandstorm.exchange.api.msg.UserInjectStepMsg getUserInjectSteps(int index) {
    return userInjectSteps_.get(index);
  }
  /**
   * <code>repeated .UserInjectStepMsg user_inject_steps = 2;</code>
   */
  public io.sandstorm.exchange.api.msg.UserInjectStepMsgOrBuilder getUserInjectStepsOrBuilder(
      int index) {
    return userInjectSteps_.get(index);
  }

  public static final int RPS_THROT_STEPS_FIELD_NUMBER = 3;
  private java.util.List<io.sandstorm.exchange.api.msg.RpsThrotStepMsg> rpsThrotSteps_;
  /**
   * <code>repeated .RpsThrotStepMsg rps_throt_steps = 3;</code>
   */
  public java.util.List<io.sandstorm.exchange.api.msg.RpsThrotStepMsg> getRpsThrotStepsList() {
    return rpsThrotSteps_;
  }
  /**
   * <code>repeated .RpsThrotStepMsg rps_throt_steps = 3;</code>
   */
  public java.util.List<? extends io.sandstorm.exchange.api.msg.RpsThrotStepMsgOrBuilder> 
      getRpsThrotStepsOrBuilderList() {
    return rpsThrotSteps_;
  }
  /**
   * <code>repeated .RpsThrotStepMsg rps_throt_steps = 3;</code>
   */
  public int getRpsThrotStepsCount() {
    return rpsThrotSteps_.size();
  }
  /**
   * <code>repeated .RpsThrotStepMsg rps_throt_steps = 3;</code>
   */
  public io.sandstorm.exchange.api.msg.RpsThrotStepMsg getRpsThrotSteps(int index) {
    return rpsThrotSteps_.get(index);
  }
  /**
   * <code>repeated .RpsThrotStepMsg rps_throt_steps = 3;</code>
   */
  public io.sandstorm.exchange.api.msg.RpsThrotStepMsgOrBuilder getRpsThrotStepsOrBuilder(
      int index) {
    return rpsThrotSteps_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (scnRepeatTimes_ != 0L) {
      output.writeInt64(1, scnRepeatTimes_);
    }
    for (int i = 0; i < userInjectSteps_.size(); i++) {
      output.writeMessage(2, userInjectSteps_.get(i));
    }
    for (int i = 0; i < rpsThrotSteps_.size(); i++) {
      output.writeMessage(3, rpsThrotSteps_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (scnRepeatTimes_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, scnRepeatTimes_);
    }
    for (int i = 0; i < userInjectSteps_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, userInjectSteps_.get(i));
    }
    for (int i = 0; i < rpsThrotSteps_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, rpsThrotSteps_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.sandstorm.exchange.api.msg.LoadProfileMsg)) {
      return super.equals(obj);
    }
    io.sandstorm.exchange.api.msg.LoadProfileMsg other = (io.sandstorm.exchange.api.msg.LoadProfileMsg) obj;

    boolean result = true;
    result = result && (getScnRepeatTimes()
        == other.getScnRepeatTimes());
    result = result && getUserInjectStepsList()
        .equals(other.getUserInjectStepsList());
    result = result && getRpsThrotStepsList()
        .equals(other.getRpsThrotStepsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SCN_REPEAT_TIMES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getScnRepeatTimes());
    if (getUserInjectStepsCount() > 0) {
      hash = (37 * hash) + USER_INJECT_STEPS_FIELD_NUMBER;
      hash = (53 * hash) + getUserInjectStepsList().hashCode();
    }
    if (getRpsThrotStepsCount() > 0) {
      hash = (37 * hash) + RPS_THROT_STEPS_FIELD_NUMBER;
      hash = (53 * hash) + getRpsThrotStepsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.sandstorm.exchange.api.msg.LoadProfileMsg parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.sandstorm.exchange.api.msg.LoadProfileMsg parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.sandstorm.exchange.api.msg.LoadProfileMsg parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.sandstorm.exchange.api.msg.LoadProfileMsg parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.sandstorm.exchange.api.msg.LoadProfileMsg parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.sandstorm.exchange.api.msg.LoadProfileMsg parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.sandstorm.exchange.api.msg.LoadProfileMsg parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.sandstorm.exchange.api.msg.LoadProfileMsg parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.sandstorm.exchange.api.msg.LoadProfileMsg parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.sandstorm.exchange.api.msg.LoadProfileMsg parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.sandstorm.exchange.api.msg.LoadProfileMsg parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.sandstorm.exchange.api.msg.LoadProfileMsg parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.sandstorm.exchange.api.msg.LoadProfileMsg prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code LoadProfileMsg}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:LoadProfileMsg)
      io.sandstorm.exchange.api.msg.LoadProfileMsgOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.sandstorm.exchange.api.msg.TestTaskProto.internal_static_LoadProfileMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.sandstorm.exchange.api.msg.TestTaskProto.internal_static_LoadProfileMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.sandstorm.exchange.api.msg.LoadProfileMsg.class, io.sandstorm.exchange.api.msg.LoadProfileMsg.Builder.class);
    }

    // Construct using io.sandstorm.exchange.api.msg.LoadProfileMsg.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getUserInjectStepsFieldBuilder();
        getRpsThrotStepsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      scnRepeatTimes_ = 0L;

      if (userInjectStepsBuilder_ == null) {
        userInjectSteps_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        userInjectStepsBuilder_.clear();
      }
      if (rpsThrotStepsBuilder_ == null) {
        rpsThrotSteps_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        rpsThrotStepsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.sandstorm.exchange.api.msg.TestTaskProto.internal_static_LoadProfileMsg_descriptor;
    }

    public io.sandstorm.exchange.api.msg.LoadProfileMsg getDefaultInstanceForType() {
      return io.sandstorm.exchange.api.msg.LoadProfileMsg.getDefaultInstance();
    }

    public io.sandstorm.exchange.api.msg.LoadProfileMsg build() {
      io.sandstorm.exchange.api.msg.LoadProfileMsg result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.sandstorm.exchange.api.msg.LoadProfileMsg buildPartial() {
      io.sandstorm.exchange.api.msg.LoadProfileMsg result = new io.sandstorm.exchange.api.msg.LoadProfileMsg(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.scnRepeatTimes_ = scnRepeatTimes_;
      if (userInjectStepsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          userInjectSteps_ = java.util.Collections.unmodifiableList(userInjectSteps_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.userInjectSteps_ = userInjectSteps_;
      } else {
        result.userInjectSteps_ = userInjectStepsBuilder_.build();
      }
      if (rpsThrotStepsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          rpsThrotSteps_ = java.util.Collections.unmodifiableList(rpsThrotSteps_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.rpsThrotSteps_ = rpsThrotSteps_;
      } else {
        result.rpsThrotSteps_ = rpsThrotStepsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.sandstorm.exchange.api.msg.LoadProfileMsg) {
        return mergeFrom((io.sandstorm.exchange.api.msg.LoadProfileMsg)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.sandstorm.exchange.api.msg.LoadProfileMsg other) {
      if (other == io.sandstorm.exchange.api.msg.LoadProfileMsg.getDefaultInstance()) return this;
      if (other.getScnRepeatTimes() != 0L) {
        setScnRepeatTimes(other.getScnRepeatTimes());
      }
      if (userInjectStepsBuilder_ == null) {
        if (!other.userInjectSteps_.isEmpty()) {
          if (userInjectSteps_.isEmpty()) {
            userInjectSteps_ = other.userInjectSteps_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureUserInjectStepsIsMutable();
            userInjectSteps_.addAll(other.userInjectSteps_);
          }
          onChanged();
        }
      } else {
        if (!other.userInjectSteps_.isEmpty()) {
          if (userInjectStepsBuilder_.isEmpty()) {
            userInjectStepsBuilder_.dispose();
            userInjectStepsBuilder_ = null;
            userInjectSteps_ = other.userInjectSteps_;
            bitField0_ = (bitField0_ & ~0x00000002);
            userInjectStepsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getUserInjectStepsFieldBuilder() : null;
          } else {
            userInjectStepsBuilder_.addAllMessages(other.userInjectSteps_);
          }
        }
      }
      if (rpsThrotStepsBuilder_ == null) {
        if (!other.rpsThrotSteps_.isEmpty()) {
          if (rpsThrotSteps_.isEmpty()) {
            rpsThrotSteps_ = other.rpsThrotSteps_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureRpsThrotStepsIsMutable();
            rpsThrotSteps_.addAll(other.rpsThrotSteps_);
          }
          onChanged();
        }
      } else {
        if (!other.rpsThrotSteps_.isEmpty()) {
          if (rpsThrotStepsBuilder_.isEmpty()) {
            rpsThrotStepsBuilder_.dispose();
            rpsThrotStepsBuilder_ = null;
            rpsThrotSteps_ = other.rpsThrotSteps_;
            bitField0_ = (bitField0_ & ~0x00000004);
            rpsThrotStepsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRpsThrotStepsFieldBuilder() : null;
          } else {
            rpsThrotStepsBuilder_.addAllMessages(other.rpsThrotSteps_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.sandstorm.exchange.api.msg.LoadProfileMsg parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.sandstorm.exchange.api.msg.LoadProfileMsg) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long scnRepeatTimes_ ;
    /**
     * <code>int64 scn_repeat_times = 1;</code>
     */
    public long getScnRepeatTimes() {
      return scnRepeatTimes_;
    }
    /**
     * <code>int64 scn_repeat_times = 1;</code>
     */
    public Builder setScnRepeatTimes(long value) {
      
      scnRepeatTimes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 scn_repeat_times = 1;</code>
     */
    public Builder clearScnRepeatTimes() {
      
      scnRepeatTimes_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<io.sandstorm.exchange.api.msg.UserInjectStepMsg> userInjectSteps_ =
      java.util.Collections.emptyList();
    private void ensureUserInjectStepsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        userInjectSteps_ = new java.util.ArrayList<io.sandstorm.exchange.api.msg.UserInjectStepMsg>(userInjectSteps_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.sandstorm.exchange.api.msg.UserInjectStepMsg, io.sandstorm.exchange.api.msg.UserInjectStepMsg.Builder, io.sandstorm.exchange.api.msg.UserInjectStepMsgOrBuilder> userInjectStepsBuilder_;

    /**
     * <code>repeated .UserInjectStepMsg user_inject_steps = 2;</code>
     */
    public java.util.List<io.sandstorm.exchange.api.msg.UserInjectStepMsg> getUserInjectStepsList() {
      if (userInjectStepsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(userInjectSteps_);
      } else {
        return userInjectStepsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .UserInjectStepMsg user_inject_steps = 2;</code>
     */
    public int getUserInjectStepsCount() {
      if (userInjectStepsBuilder_ == null) {
        return userInjectSteps_.size();
      } else {
        return userInjectStepsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .UserInjectStepMsg user_inject_steps = 2;</code>
     */
    public io.sandstorm.exchange.api.msg.UserInjectStepMsg getUserInjectSteps(int index) {
      if (userInjectStepsBuilder_ == null) {
        return userInjectSteps_.get(index);
      } else {
        return userInjectStepsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .UserInjectStepMsg user_inject_steps = 2;</code>
     */
    public Builder setUserInjectSteps(
        int index, io.sandstorm.exchange.api.msg.UserInjectStepMsg value) {
      if (userInjectStepsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserInjectStepsIsMutable();
        userInjectSteps_.set(index, value);
        onChanged();
      } else {
        userInjectStepsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .UserInjectStepMsg user_inject_steps = 2;</code>
     */
    public Builder setUserInjectSteps(
        int index, io.sandstorm.exchange.api.msg.UserInjectStepMsg.Builder builderForValue) {
      if (userInjectStepsBuilder_ == null) {
        ensureUserInjectStepsIsMutable();
        userInjectSteps_.set(index, builderForValue.build());
        onChanged();
      } else {
        userInjectStepsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .UserInjectStepMsg user_inject_steps = 2;</code>
     */
    public Builder addUserInjectSteps(io.sandstorm.exchange.api.msg.UserInjectStepMsg value) {
      if (userInjectStepsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserInjectStepsIsMutable();
        userInjectSteps_.add(value);
        onChanged();
      } else {
        userInjectStepsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .UserInjectStepMsg user_inject_steps = 2;</code>
     */
    public Builder addUserInjectSteps(
        int index, io.sandstorm.exchange.api.msg.UserInjectStepMsg value) {
      if (userInjectStepsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserInjectStepsIsMutable();
        userInjectSteps_.add(index, value);
        onChanged();
      } else {
        userInjectStepsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .UserInjectStepMsg user_inject_steps = 2;</code>
     */
    public Builder addUserInjectSteps(
        io.sandstorm.exchange.api.msg.UserInjectStepMsg.Builder builderForValue) {
      if (userInjectStepsBuilder_ == null) {
        ensureUserInjectStepsIsMutable();
        userInjectSteps_.add(builderForValue.build());
        onChanged();
      } else {
        userInjectStepsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .UserInjectStepMsg user_inject_steps = 2;</code>
     */
    public Builder addUserInjectSteps(
        int index, io.sandstorm.exchange.api.msg.UserInjectStepMsg.Builder builderForValue) {
      if (userInjectStepsBuilder_ == null) {
        ensureUserInjectStepsIsMutable();
        userInjectSteps_.add(index, builderForValue.build());
        onChanged();
      } else {
        userInjectStepsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .UserInjectStepMsg user_inject_steps = 2;</code>
     */
    public Builder addAllUserInjectSteps(
        java.lang.Iterable<? extends io.sandstorm.exchange.api.msg.UserInjectStepMsg> values) {
      if (userInjectStepsBuilder_ == null) {
        ensureUserInjectStepsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, userInjectSteps_);
        onChanged();
      } else {
        userInjectStepsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .UserInjectStepMsg user_inject_steps = 2;</code>
     */
    public Builder clearUserInjectSteps() {
      if (userInjectStepsBuilder_ == null) {
        userInjectSteps_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        userInjectStepsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .UserInjectStepMsg user_inject_steps = 2;</code>
     */
    public Builder removeUserInjectSteps(int index) {
      if (userInjectStepsBuilder_ == null) {
        ensureUserInjectStepsIsMutable();
        userInjectSteps_.remove(index);
        onChanged();
      } else {
        userInjectStepsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .UserInjectStepMsg user_inject_steps = 2;</code>
     */
    public io.sandstorm.exchange.api.msg.UserInjectStepMsg.Builder getUserInjectStepsBuilder(
        int index) {
      return getUserInjectStepsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .UserInjectStepMsg user_inject_steps = 2;</code>
     */
    public io.sandstorm.exchange.api.msg.UserInjectStepMsgOrBuilder getUserInjectStepsOrBuilder(
        int index) {
      if (userInjectStepsBuilder_ == null) {
        return userInjectSteps_.get(index);  } else {
        return userInjectStepsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .UserInjectStepMsg user_inject_steps = 2;</code>
     */
    public java.util.List<? extends io.sandstorm.exchange.api.msg.UserInjectStepMsgOrBuilder> 
         getUserInjectStepsOrBuilderList() {
      if (userInjectStepsBuilder_ != null) {
        return userInjectStepsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(userInjectSteps_);
      }
    }
    /**
     * <code>repeated .UserInjectStepMsg user_inject_steps = 2;</code>
     */
    public io.sandstorm.exchange.api.msg.UserInjectStepMsg.Builder addUserInjectStepsBuilder() {
      return getUserInjectStepsFieldBuilder().addBuilder(
          io.sandstorm.exchange.api.msg.UserInjectStepMsg.getDefaultInstance());
    }
    /**
     * <code>repeated .UserInjectStepMsg user_inject_steps = 2;</code>
     */
    public io.sandstorm.exchange.api.msg.UserInjectStepMsg.Builder addUserInjectStepsBuilder(
        int index) {
      return getUserInjectStepsFieldBuilder().addBuilder(
          index, io.sandstorm.exchange.api.msg.UserInjectStepMsg.getDefaultInstance());
    }
    /**
     * <code>repeated .UserInjectStepMsg user_inject_steps = 2;</code>
     */
    public java.util.List<io.sandstorm.exchange.api.msg.UserInjectStepMsg.Builder> 
         getUserInjectStepsBuilderList() {
      return getUserInjectStepsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.sandstorm.exchange.api.msg.UserInjectStepMsg, io.sandstorm.exchange.api.msg.UserInjectStepMsg.Builder, io.sandstorm.exchange.api.msg.UserInjectStepMsgOrBuilder> 
        getUserInjectStepsFieldBuilder() {
      if (userInjectStepsBuilder_ == null) {
        userInjectStepsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.sandstorm.exchange.api.msg.UserInjectStepMsg, io.sandstorm.exchange.api.msg.UserInjectStepMsg.Builder, io.sandstorm.exchange.api.msg.UserInjectStepMsgOrBuilder>(
                userInjectSteps_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        userInjectSteps_ = null;
      }
      return userInjectStepsBuilder_;
    }

    private java.util.List<io.sandstorm.exchange.api.msg.RpsThrotStepMsg> rpsThrotSteps_ =
      java.util.Collections.emptyList();
    private void ensureRpsThrotStepsIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        rpsThrotSteps_ = new java.util.ArrayList<io.sandstorm.exchange.api.msg.RpsThrotStepMsg>(rpsThrotSteps_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.sandstorm.exchange.api.msg.RpsThrotStepMsg, io.sandstorm.exchange.api.msg.RpsThrotStepMsg.Builder, io.sandstorm.exchange.api.msg.RpsThrotStepMsgOrBuilder> rpsThrotStepsBuilder_;

    /**
     * <code>repeated .RpsThrotStepMsg rps_throt_steps = 3;</code>
     */
    public java.util.List<io.sandstorm.exchange.api.msg.RpsThrotStepMsg> getRpsThrotStepsList() {
      if (rpsThrotStepsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(rpsThrotSteps_);
      } else {
        return rpsThrotStepsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .RpsThrotStepMsg rps_throt_steps = 3;</code>
     */
    public int getRpsThrotStepsCount() {
      if (rpsThrotStepsBuilder_ == null) {
        return rpsThrotSteps_.size();
      } else {
        return rpsThrotStepsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .RpsThrotStepMsg rps_throt_steps = 3;</code>
     */
    public io.sandstorm.exchange.api.msg.RpsThrotStepMsg getRpsThrotSteps(int index) {
      if (rpsThrotStepsBuilder_ == null) {
        return rpsThrotSteps_.get(index);
      } else {
        return rpsThrotStepsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .RpsThrotStepMsg rps_throt_steps = 3;</code>
     */
    public Builder setRpsThrotSteps(
        int index, io.sandstorm.exchange.api.msg.RpsThrotStepMsg value) {
      if (rpsThrotStepsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRpsThrotStepsIsMutable();
        rpsThrotSteps_.set(index, value);
        onChanged();
      } else {
        rpsThrotStepsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .RpsThrotStepMsg rps_throt_steps = 3;</code>
     */
    public Builder setRpsThrotSteps(
        int index, io.sandstorm.exchange.api.msg.RpsThrotStepMsg.Builder builderForValue) {
      if (rpsThrotStepsBuilder_ == null) {
        ensureRpsThrotStepsIsMutable();
        rpsThrotSteps_.set(index, builderForValue.build());
        onChanged();
      } else {
        rpsThrotStepsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .RpsThrotStepMsg rps_throt_steps = 3;</code>
     */
    public Builder addRpsThrotSteps(io.sandstorm.exchange.api.msg.RpsThrotStepMsg value) {
      if (rpsThrotStepsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRpsThrotStepsIsMutable();
        rpsThrotSteps_.add(value);
        onChanged();
      } else {
        rpsThrotStepsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .RpsThrotStepMsg rps_throt_steps = 3;</code>
     */
    public Builder addRpsThrotSteps(
        int index, io.sandstorm.exchange.api.msg.RpsThrotStepMsg value) {
      if (rpsThrotStepsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRpsThrotStepsIsMutable();
        rpsThrotSteps_.add(index, value);
        onChanged();
      } else {
        rpsThrotStepsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .RpsThrotStepMsg rps_throt_steps = 3;</code>
     */
    public Builder addRpsThrotSteps(
        io.sandstorm.exchange.api.msg.RpsThrotStepMsg.Builder builderForValue) {
      if (rpsThrotStepsBuilder_ == null) {
        ensureRpsThrotStepsIsMutable();
        rpsThrotSteps_.add(builderForValue.build());
        onChanged();
      } else {
        rpsThrotStepsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .RpsThrotStepMsg rps_throt_steps = 3;</code>
     */
    public Builder addRpsThrotSteps(
        int index, io.sandstorm.exchange.api.msg.RpsThrotStepMsg.Builder builderForValue) {
      if (rpsThrotStepsBuilder_ == null) {
        ensureRpsThrotStepsIsMutable();
        rpsThrotSteps_.add(index, builderForValue.build());
        onChanged();
      } else {
        rpsThrotStepsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .RpsThrotStepMsg rps_throt_steps = 3;</code>
     */
    public Builder addAllRpsThrotSteps(
        java.lang.Iterable<? extends io.sandstorm.exchange.api.msg.RpsThrotStepMsg> values) {
      if (rpsThrotStepsBuilder_ == null) {
        ensureRpsThrotStepsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, rpsThrotSteps_);
        onChanged();
      } else {
        rpsThrotStepsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .RpsThrotStepMsg rps_throt_steps = 3;</code>
     */
    public Builder clearRpsThrotSteps() {
      if (rpsThrotStepsBuilder_ == null) {
        rpsThrotSteps_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        rpsThrotStepsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .RpsThrotStepMsg rps_throt_steps = 3;</code>
     */
    public Builder removeRpsThrotSteps(int index) {
      if (rpsThrotStepsBuilder_ == null) {
        ensureRpsThrotStepsIsMutable();
        rpsThrotSteps_.remove(index);
        onChanged();
      } else {
        rpsThrotStepsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .RpsThrotStepMsg rps_throt_steps = 3;</code>
     */
    public io.sandstorm.exchange.api.msg.RpsThrotStepMsg.Builder getRpsThrotStepsBuilder(
        int index) {
      return getRpsThrotStepsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .RpsThrotStepMsg rps_throt_steps = 3;</code>
     */
    public io.sandstorm.exchange.api.msg.RpsThrotStepMsgOrBuilder getRpsThrotStepsOrBuilder(
        int index) {
      if (rpsThrotStepsBuilder_ == null) {
        return rpsThrotSteps_.get(index);  } else {
        return rpsThrotStepsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .RpsThrotStepMsg rps_throt_steps = 3;</code>
     */
    public java.util.List<? extends io.sandstorm.exchange.api.msg.RpsThrotStepMsgOrBuilder> 
         getRpsThrotStepsOrBuilderList() {
      if (rpsThrotStepsBuilder_ != null) {
        return rpsThrotStepsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(rpsThrotSteps_);
      }
    }
    /**
     * <code>repeated .RpsThrotStepMsg rps_throt_steps = 3;</code>
     */
    public io.sandstorm.exchange.api.msg.RpsThrotStepMsg.Builder addRpsThrotStepsBuilder() {
      return getRpsThrotStepsFieldBuilder().addBuilder(
          io.sandstorm.exchange.api.msg.RpsThrotStepMsg.getDefaultInstance());
    }
    /**
     * <code>repeated .RpsThrotStepMsg rps_throt_steps = 3;</code>
     */
    public io.sandstorm.exchange.api.msg.RpsThrotStepMsg.Builder addRpsThrotStepsBuilder(
        int index) {
      return getRpsThrotStepsFieldBuilder().addBuilder(
          index, io.sandstorm.exchange.api.msg.RpsThrotStepMsg.getDefaultInstance());
    }
    /**
     * <code>repeated .RpsThrotStepMsg rps_throt_steps = 3;</code>
     */
    public java.util.List<io.sandstorm.exchange.api.msg.RpsThrotStepMsg.Builder> 
         getRpsThrotStepsBuilderList() {
      return getRpsThrotStepsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.sandstorm.exchange.api.msg.RpsThrotStepMsg, io.sandstorm.exchange.api.msg.RpsThrotStepMsg.Builder, io.sandstorm.exchange.api.msg.RpsThrotStepMsgOrBuilder> 
        getRpsThrotStepsFieldBuilder() {
      if (rpsThrotStepsBuilder_ == null) {
        rpsThrotStepsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.sandstorm.exchange.api.msg.RpsThrotStepMsg, io.sandstorm.exchange.api.msg.RpsThrotStepMsg.Builder, io.sandstorm.exchange.api.msg.RpsThrotStepMsgOrBuilder>(
                rpsThrotSteps_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        rpsThrotSteps_ = null;
      }
      return rpsThrotStepsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:LoadProfileMsg)
  }

  // @@protoc_insertion_point(class_scope:LoadProfileMsg)
  private static final io.sandstorm.exchange.api.msg.LoadProfileMsg DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.sandstorm.exchange.api.msg.LoadProfileMsg();
  }

  public static io.sandstorm.exchange.api.msg.LoadProfileMsg getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LoadProfileMsg>
      PARSER = new com.google.protobuf.AbstractParser<LoadProfileMsg>() {
    public LoadProfileMsg parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LoadProfileMsg(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LoadProfileMsg> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LoadProfileMsg> getParserForType() {
    return PARSER;
  }

  public io.sandstorm.exchange.api.msg.LoadProfileMsg getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

