// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package io.sandstorm.exchange.api.msg;

public interface ResultNotifyMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResultNotifyMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.ResultMsg result = 2;</code>
   */
  boolean hasResult();
  /**
   * <code>.ResultMsg result = 2;</code>
   */
  io.sandstorm.exchange.api.msg.ResultMsg getResult();
  /**
   * <code>.ResultMsg result = 2;</code>
   */
  io.sandstorm.exchange.api.msg.ResultMsgOrBuilder getResultOrBuilder();
}
