// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package io.sandstorm.exchange.api.msg;

public interface RpsThrotStepMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RpsThrotStepMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 ramp_time = 1;</code>
   */
  long getRampTime();

  /**
   * <code>int64 to_rps = 2;</code>
   */
  long getToRps();

  /**
   * <code>int64 hold_time = 3;</code>
   */
  long getHoldTime();
}
