// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package io.sandstorm.exchange.api.msg;

public interface TestScriptMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TestScriptMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string jar_alias = 1;</code>
   */
  java.lang.String getJarAlias();
  /**
   * <code>string jar_alias = 1;</code>
   */
  com.google.protobuf.ByteString
      getJarAliasBytes();

  /**
   * <code>string jar_url = 2;</code>
   */
  java.lang.String getJarUrl();
  /**
   * <code>string jar_url = 2;</code>
   */
  com.google.protobuf.ByteString
      getJarUrlBytes();
}
