// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package io.sandstorm.exchange.api.msg;

/**
 * Protobuf type {@code TestJobMsg}
 */
public  final class TestJobMsg extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TestJobMsg)
    TestJobMsgOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TestJobMsg.newBuilder() to construct.
  private TestJobMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TestJobMsg() {
    id_ = "";
    superJobId_ = "";
    simulationToRun_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TestJobMsg(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            superJobId_ = s;
            break;
          }
          case 26: {
            io.sandstorm.exchange.api.msg.TestScriptMsg.Builder subBuilder = null;
            if (script_ != null) {
              subBuilder = script_.toBuilder();
            }
            script_ = input.readMessage(io.sandstorm.exchange.api.msg.TestScriptMsg.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(script_);
              script_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            simulationToRun_ = s;
            break;
          }
          case 42: {
            io.sandstorm.exchange.api.msg.DataSetMsg.Builder subBuilder = null;
            if (dataSet_ != null) {
              subBuilder = dataSet_.toBuilder();
            }
            dataSet_ = input.readMessage(io.sandstorm.exchange.api.msg.DataSetMsg.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dataSet_);
              dataSet_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            io.sandstorm.exchange.api.msg.LoadProfileMsg.Builder subBuilder = null;
            if (loadProfile_ != null) {
              subBuilder = loadProfile_.toBuilder();
            }
            loadProfile_ = input.readMessage(io.sandstorm.exchange.api.msg.LoadProfileMsg.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(loadProfile_);
              loadProfile_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.sandstorm.exchange.api.msg.TestTaskProto.internal_static_TestJobMsg_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.sandstorm.exchange.api.msg.TestTaskProto.internal_static_TestJobMsg_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.sandstorm.exchange.api.msg.TestJobMsg.class, io.sandstorm.exchange.api.msg.TestJobMsg.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUPER_JOB_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object superJobId_;
  /**
   * <code>string super_job_id = 2;</code>
   */
  public java.lang.String getSuperJobId() {
    java.lang.Object ref = superJobId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      superJobId_ = s;
      return s;
    }
  }
  /**
   * <code>string super_job_id = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSuperJobIdBytes() {
    java.lang.Object ref = superJobId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      superJobId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SCRIPT_FIELD_NUMBER = 3;
  private io.sandstorm.exchange.api.msg.TestScriptMsg script_;
  /**
   * <code>.TestScriptMsg script = 3;</code>
   */
  public boolean hasScript() {
    return script_ != null;
  }
  /**
   * <code>.TestScriptMsg script = 3;</code>
   */
  public io.sandstorm.exchange.api.msg.TestScriptMsg getScript() {
    return script_ == null ? io.sandstorm.exchange.api.msg.TestScriptMsg.getDefaultInstance() : script_;
  }
  /**
   * <code>.TestScriptMsg script = 3;</code>
   */
  public io.sandstorm.exchange.api.msg.TestScriptMsgOrBuilder getScriptOrBuilder() {
    return getScript();
  }

  public static final int SIMULATION_TO_RUN_FIELD_NUMBER = 4;
  private volatile java.lang.Object simulationToRun_;
  /**
   * <code>string simulation_to_run = 4;</code>
   */
  public java.lang.String getSimulationToRun() {
    java.lang.Object ref = simulationToRun_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      simulationToRun_ = s;
      return s;
    }
  }
  /**
   * <code>string simulation_to_run = 4;</code>
   */
  public com.google.protobuf.ByteString
      getSimulationToRunBytes() {
    java.lang.Object ref = simulationToRun_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      simulationToRun_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATA_SET_FIELD_NUMBER = 5;
  private io.sandstorm.exchange.api.msg.DataSetMsg dataSet_;
  /**
   * <code>.DataSetMsg data_set = 5;</code>
   */
  public boolean hasDataSet() {
    return dataSet_ != null;
  }
  /**
   * <code>.DataSetMsg data_set = 5;</code>
   */
  public io.sandstorm.exchange.api.msg.DataSetMsg getDataSet() {
    return dataSet_ == null ? io.sandstorm.exchange.api.msg.DataSetMsg.getDefaultInstance() : dataSet_;
  }
  /**
   * <code>.DataSetMsg data_set = 5;</code>
   */
  public io.sandstorm.exchange.api.msg.DataSetMsgOrBuilder getDataSetOrBuilder() {
    return getDataSet();
  }

  public static final int LOAD_PROFILE_FIELD_NUMBER = 6;
  private io.sandstorm.exchange.api.msg.LoadProfileMsg loadProfile_;
  /**
   * <code>.LoadProfileMsg load_profile = 6;</code>
   */
  public boolean hasLoadProfile() {
    return loadProfile_ != null;
  }
  /**
   * <code>.LoadProfileMsg load_profile = 6;</code>
   */
  public io.sandstorm.exchange.api.msg.LoadProfileMsg getLoadProfile() {
    return loadProfile_ == null ? io.sandstorm.exchange.api.msg.LoadProfileMsg.getDefaultInstance() : loadProfile_;
  }
  /**
   * <code>.LoadProfileMsg load_profile = 6;</code>
   */
  public io.sandstorm.exchange.api.msg.LoadProfileMsgOrBuilder getLoadProfileOrBuilder() {
    return getLoadProfile();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!getSuperJobIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, superJobId_);
    }
    if (script_ != null) {
      output.writeMessage(3, getScript());
    }
    if (!getSimulationToRunBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, simulationToRun_);
    }
    if (dataSet_ != null) {
      output.writeMessage(5, getDataSet());
    }
    if (loadProfile_ != null) {
      output.writeMessage(6, getLoadProfile());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!getSuperJobIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, superJobId_);
    }
    if (script_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getScript());
    }
    if (!getSimulationToRunBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, simulationToRun_);
    }
    if (dataSet_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getDataSet());
    }
    if (loadProfile_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getLoadProfile());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.sandstorm.exchange.api.msg.TestJobMsg)) {
      return super.equals(obj);
    }
    io.sandstorm.exchange.api.msg.TestJobMsg other = (io.sandstorm.exchange.api.msg.TestJobMsg) obj;

    boolean result = true;
    result = result && getId()
        .equals(other.getId());
    result = result && getSuperJobId()
        .equals(other.getSuperJobId());
    result = result && (hasScript() == other.hasScript());
    if (hasScript()) {
      result = result && getScript()
          .equals(other.getScript());
    }
    result = result && getSimulationToRun()
        .equals(other.getSimulationToRun());
    result = result && (hasDataSet() == other.hasDataSet());
    if (hasDataSet()) {
      result = result && getDataSet()
          .equals(other.getDataSet());
    }
    result = result && (hasLoadProfile() == other.hasLoadProfile());
    if (hasLoadProfile()) {
      result = result && getLoadProfile()
          .equals(other.getLoadProfile());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + SUPER_JOB_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSuperJobId().hashCode();
    if (hasScript()) {
      hash = (37 * hash) + SCRIPT_FIELD_NUMBER;
      hash = (53 * hash) + getScript().hashCode();
    }
    hash = (37 * hash) + SIMULATION_TO_RUN_FIELD_NUMBER;
    hash = (53 * hash) + getSimulationToRun().hashCode();
    if (hasDataSet()) {
      hash = (37 * hash) + DATA_SET_FIELD_NUMBER;
      hash = (53 * hash) + getDataSet().hashCode();
    }
    if (hasLoadProfile()) {
      hash = (37 * hash) + LOAD_PROFILE_FIELD_NUMBER;
      hash = (53 * hash) + getLoadProfile().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.sandstorm.exchange.api.msg.TestJobMsg parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.sandstorm.exchange.api.msg.TestJobMsg parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.sandstorm.exchange.api.msg.TestJobMsg parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.sandstorm.exchange.api.msg.TestJobMsg parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.sandstorm.exchange.api.msg.TestJobMsg parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.sandstorm.exchange.api.msg.TestJobMsg parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.sandstorm.exchange.api.msg.TestJobMsg parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.sandstorm.exchange.api.msg.TestJobMsg parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.sandstorm.exchange.api.msg.TestJobMsg parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.sandstorm.exchange.api.msg.TestJobMsg parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.sandstorm.exchange.api.msg.TestJobMsg parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.sandstorm.exchange.api.msg.TestJobMsg parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.sandstorm.exchange.api.msg.TestJobMsg prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TestJobMsg}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TestJobMsg)
      io.sandstorm.exchange.api.msg.TestJobMsgOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.sandstorm.exchange.api.msg.TestTaskProto.internal_static_TestJobMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.sandstorm.exchange.api.msg.TestTaskProto.internal_static_TestJobMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.sandstorm.exchange.api.msg.TestJobMsg.class, io.sandstorm.exchange.api.msg.TestJobMsg.Builder.class);
    }

    // Construct using io.sandstorm.exchange.api.msg.TestJobMsg.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = "";

      superJobId_ = "";

      if (scriptBuilder_ == null) {
        script_ = null;
      } else {
        script_ = null;
        scriptBuilder_ = null;
      }
      simulationToRun_ = "";

      if (dataSetBuilder_ == null) {
        dataSet_ = null;
      } else {
        dataSet_ = null;
        dataSetBuilder_ = null;
      }
      if (loadProfileBuilder_ == null) {
        loadProfile_ = null;
      } else {
        loadProfile_ = null;
        loadProfileBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.sandstorm.exchange.api.msg.TestTaskProto.internal_static_TestJobMsg_descriptor;
    }

    public io.sandstorm.exchange.api.msg.TestJobMsg getDefaultInstanceForType() {
      return io.sandstorm.exchange.api.msg.TestJobMsg.getDefaultInstance();
    }

    public io.sandstorm.exchange.api.msg.TestJobMsg build() {
      io.sandstorm.exchange.api.msg.TestJobMsg result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.sandstorm.exchange.api.msg.TestJobMsg buildPartial() {
      io.sandstorm.exchange.api.msg.TestJobMsg result = new io.sandstorm.exchange.api.msg.TestJobMsg(this);
      result.id_ = id_;
      result.superJobId_ = superJobId_;
      if (scriptBuilder_ == null) {
        result.script_ = script_;
      } else {
        result.script_ = scriptBuilder_.build();
      }
      result.simulationToRun_ = simulationToRun_;
      if (dataSetBuilder_ == null) {
        result.dataSet_ = dataSet_;
      } else {
        result.dataSet_ = dataSetBuilder_.build();
      }
      if (loadProfileBuilder_ == null) {
        result.loadProfile_ = loadProfile_;
      } else {
        result.loadProfile_ = loadProfileBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.sandstorm.exchange.api.msg.TestJobMsg) {
        return mergeFrom((io.sandstorm.exchange.api.msg.TestJobMsg)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.sandstorm.exchange.api.msg.TestJobMsg other) {
      if (other == io.sandstorm.exchange.api.msg.TestJobMsg.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getSuperJobId().isEmpty()) {
        superJobId_ = other.superJobId_;
        onChanged();
      }
      if (other.hasScript()) {
        mergeScript(other.getScript());
      }
      if (!other.getSimulationToRun().isEmpty()) {
        simulationToRun_ = other.simulationToRun_;
        onChanged();
      }
      if (other.hasDataSet()) {
        mergeDataSet(other.getDataSet());
      }
      if (other.hasLoadProfile()) {
        mergeLoadProfile(other.getLoadProfile());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.sandstorm.exchange.api.msg.TestJobMsg parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.sandstorm.exchange.api.msg.TestJobMsg) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object superJobId_ = "";
    /**
     * <code>string super_job_id = 2;</code>
     */
    public java.lang.String getSuperJobId() {
      java.lang.Object ref = superJobId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        superJobId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string super_job_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSuperJobIdBytes() {
      java.lang.Object ref = superJobId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        superJobId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string super_job_id = 2;</code>
     */
    public Builder setSuperJobId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      superJobId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string super_job_id = 2;</code>
     */
    public Builder clearSuperJobId() {
      
      superJobId_ = getDefaultInstance().getSuperJobId();
      onChanged();
      return this;
    }
    /**
     * <code>string super_job_id = 2;</code>
     */
    public Builder setSuperJobIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      superJobId_ = value;
      onChanged();
      return this;
    }

    private io.sandstorm.exchange.api.msg.TestScriptMsg script_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.sandstorm.exchange.api.msg.TestScriptMsg, io.sandstorm.exchange.api.msg.TestScriptMsg.Builder, io.sandstorm.exchange.api.msg.TestScriptMsgOrBuilder> scriptBuilder_;
    /**
     * <code>.TestScriptMsg script = 3;</code>
     */
    public boolean hasScript() {
      return scriptBuilder_ != null || script_ != null;
    }
    /**
     * <code>.TestScriptMsg script = 3;</code>
     */
    public io.sandstorm.exchange.api.msg.TestScriptMsg getScript() {
      if (scriptBuilder_ == null) {
        return script_ == null ? io.sandstorm.exchange.api.msg.TestScriptMsg.getDefaultInstance() : script_;
      } else {
        return scriptBuilder_.getMessage();
      }
    }
    /**
     * <code>.TestScriptMsg script = 3;</code>
     */
    public Builder setScript(io.sandstorm.exchange.api.msg.TestScriptMsg value) {
      if (scriptBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        script_ = value;
        onChanged();
      } else {
        scriptBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.TestScriptMsg script = 3;</code>
     */
    public Builder setScript(
        io.sandstorm.exchange.api.msg.TestScriptMsg.Builder builderForValue) {
      if (scriptBuilder_ == null) {
        script_ = builderForValue.build();
        onChanged();
      } else {
        scriptBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.TestScriptMsg script = 3;</code>
     */
    public Builder mergeScript(io.sandstorm.exchange.api.msg.TestScriptMsg value) {
      if (scriptBuilder_ == null) {
        if (script_ != null) {
          script_ =
            io.sandstorm.exchange.api.msg.TestScriptMsg.newBuilder(script_).mergeFrom(value).buildPartial();
        } else {
          script_ = value;
        }
        onChanged();
      } else {
        scriptBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.TestScriptMsg script = 3;</code>
     */
    public Builder clearScript() {
      if (scriptBuilder_ == null) {
        script_ = null;
        onChanged();
      } else {
        script_ = null;
        scriptBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.TestScriptMsg script = 3;</code>
     */
    public io.sandstorm.exchange.api.msg.TestScriptMsg.Builder getScriptBuilder() {
      
      onChanged();
      return getScriptFieldBuilder().getBuilder();
    }
    /**
     * <code>.TestScriptMsg script = 3;</code>
     */
    public io.sandstorm.exchange.api.msg.TestScriptMsgOrBuilder getScriptOrBuilder() {
      if (scriptBuilder_ != null) {
        return scriptBuilder_.getMessageOrBuilder();
      } else {
        return script_ == null ?
            io.sandstorm.exchange.api.msg.TestScriptMsg.getDefaultInstance() : script_;
      }
    }
    /**
     * <code>.TestScriptMsg script = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.sandstorm.exchange.api.msg.TestScriptMsg, io.sandstorm.exchange.api.msg.TestScriptMsg.Builder, io.sandstorm.exchange.api.msg.TestScriptMsgOrBuilder> 
        getScriptFieldBuilder() {
      if (scriptBuilder_ == null) {
        scriptBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.sandstorm.exchange.api.msg.TestScriptMsg, io.sandstorm.exchange.api.msg.TestScriptMsg.Builder, io.sandstorm.exchange.api.msg.TestScriptMsgOrBuilder>(
                getScript(),
                getParentForChildren(),
                isClean());
        script_ = null;
      }
      return scriptBuilder_;
    }

    private java.lang.Object simulationToRun_ = "";
    /**
     * <code>string simulation_to_run = 4;</code>
     */
    public java.lang.String getSimulationToRun() {
      java.lang.Object ref = simulationToRun_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        simulationToRun_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string simulation_to_run = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSimulationToRunBytes() {
      java.lang.Object ref = simulationToRun_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        simulationToRun_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string simulation_to_run = 4;</code>
     */
    public Builder setSimulationToRun(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      simulationToRun_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string simulation_to_run = 4;</code>
     */
    public Builder clearSimulationToRun() {
      
      simulationToRun_ = getDefaultInstance().getSimulationToRun();
      onChanged();
      return this;
    }
    /**
     * <code>string simulation_to_run = 4;</code>
     */
    public Builder setSimulationToRunBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      simulationToRun_ = value;
      onChanged();
      return this;
    }

    private io.sandstorm.exchange.api.msg.DataSetMsg dataSet_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.sandstorm.exchange.api.msg.DataSetMsg, io.sandstorm.exchange.api.msg.DataSetMsg.Builder, io.sandstorm.exchange.api.msg.DataSetMsgOrBuilder> dataSetBuilder_;
    /**
     * <code>.DataSetMsg data_set = 5;</code>
     */
    public boolean hasDataSet() {
      return dataSetBuilder_ != null || dataSet_ != null;
    }
    /**
     * <code>.DataSetMsg data_set = 5;</code>
     */
    public io.sandstorm.exchange.api.msg.DataSetMsg getDataSet() {
      if (dataSetBuilder_ == null) {
        return dataSet_ == null ? io.sandstorm.exchange.api.msg.DataSetMsg.getDefaultInstance() : dataSet_;
      } else {
        return dataSetBuilder_.getMessage();
      }
    }
    /**
     * <code>.DataSetMsg data_set = 5;</code>
     */
    public Builder setDataSet(io.sandstorm.exchange.api.msg.DataSetMsg value) {
      if (dataSetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataSet_ = value;
        onChanged();
      } else {
        dataSetBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.DataSetMsg data_set = 5;</code>
     */
    public Builder setDataSet(
        io.sandstorm.exchange.api.msg.DataSetMsg.Builder builderForValue) {
      if (dataSetBuilder_ == null) {
        dataSet_ = builderForValue.build();
        onChanged();
      } else {
        dataSetBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.DataSetMsg data_set = 5;</code>
     */
    public Builder mergeDataSet(io.sandstorm.exchange.api.msg.DataSetMsg value) {
      if (dataSetBuilder_ == null) {
        if (dataSet_ != null) {
          dataSet_ =
            io.sandstorm.exchange.api.msg.DataSetMsg.newBuilder(dataSet_).mergeFrom(value).buildPartial();
        } else {
          dataSet_ = value;
        }
        onChanged();
      } else {
        dataSetBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.DataSetMsg data_set = 5;</code>
     */
    public Builder clearDataSet() {
      if (dataSetBuilder_ == null) {
        dataSet_ = null;
        onChanged();
      } else {
        dataSet_ = null;
        dataSetBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.DataSetMsg data_set = 5;</code>
     */
    public io.sandstorm.exchange.api.msg.DataSetMsg.Builder getDataSetBuilder() {
      
      onChanged();
      return getDataSetFieldBuilder().getBuilder();
    }
    /**
     * <code>.DataSetMsg data_set = 5;</code>
     */
    public io.sandstorm.exchange.api.msg.DataSetMsgOrBuilder getDataSetOrBuilder() {
      if (dataSetBuilder_ != null) {
        return dataSetBuilder_.getMessageOrBuilder();
      } else {
        return dataSet_ == null ?
            io.sandstorm.exchange.api.msg.DataSetMsg.getDefaultInstance() : dataSet_;
      }
    }
    /**
     * <code>.DataSetMsg data_set = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.sandstorm.exchange.api.msg.DataSetMsg, io.sandstorm.exchange.api.msg.DataSetMsg.Builder, io.sandstorm.exchange.api.msg.DataSetMsgOrBuilder> 
        getDataSetFieldBuilder() {
      if (dataSetBuilder_ == null) {
        dataSetBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.sandstorm.exchange.api.msg.DataSetMsg, io.sandstorm.exchange.api.msg.DataSetMsg.Builder, io.sandstorm.exchange.api.msg.DataSetMsgOrBuilder>(
                getDataSet(),
                getParentForChildren(),
                isClean());
        dataSet_ = null;
      }
      return dataSetBuilder_;
    }

    private io.sandstorm.exchange.api.msg.LoadProfileMsg loadProfile_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.sandstorm.exchange.api.msg.LoadProfileMsg, io.sandstorm.exchange.api.msg.LoadProfileMsg.Builder, io.sandstorm.exchange.api.msg.LoadProfileMsgOrBuilder> loadProfileBuilder_;
    /**
     * <code>.LoadProfileMsg load_profile = 6;</code>
     */
    public boolean hasLoadProfile() {
      return loadProfileBuilder_ != null || loadProfile_ != null;
    }
    /**
     * <code>.LoadProfileMsg load_profile = 6;</code>
     */
    public io.sandstorm.exchange.api.msg.LoadProfileMsg getLoadProfile() {
      if (loadProfileBuilder_ == null) {
        return loadProfile_ == null ? io.sandstorm.exchange.api.msg.LoadProfileMsg.getDefaultInstance() : loadProfile_;
      } else {
        return loadProfileBuilder_.getMessage();
      }
    }
    /**
     * <code>.LoadProfileMsg load_profile = 6;</code>
     */
    public Builder setLoadProfile(io.sandstorm.exchange.api.msg.LoadProfileMsg value) {
      if (loadProfileBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        loadProfile_ = value;
        onChanged();
      } else {
        loadProfileBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.LoadProfileMsg load_profile = 6;</code>
     */
    public Builder setLoadProfile(
        io.sandstorm.exchange.api.msg.LoadProfileMsg.Builder builderForValue) {
      if (loadProfileBuilder_ == null) {
        loadProfile_ = builderForValue.build();
        onChanged();
      } else {
        loadProfileBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.LoadProfileMsg load_profile = 6;</code>
     */
    public Builder mergeLoadProfile(io.sandstorm.exchange.api.msg.LoadProfileMsg value) {
      if (loadProfileBuilder_ == null) {
        if (loadProfile_ != null) {
          loadProfile_ =
            io.sandstorm.exchange.api.msg.LoadProfileMsg.newBuilder(loadProfile_).mergeFrom(value).buildPartial();
        } else {
          loadProfile_ = value;
        }
        onChanged();
      } else {
        loadProfileBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.LoadProfileMsg load_profile = 6;</code>
     */
    public Builder clearLoadProfile() {
      if (loadProfileBuilder_ == null) {
        loadProfile_ = null;
        onChanged();
      } else {
        loadProfile_ = null;
        loadProfileBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.LoadProfileMsg load_profile = 6;</code>
     */
    public io.sandstorm.exchange.api.msg.LoadProfileMsg.Builder getLoadProfileBuilder() {
      
      onChanged();
      return getLoadProfileFieldBuilder().getBuilder();
    }
    /**
     * <code>.LoadProfileMsg load_profile = 6;</code>
     */
    public io.sandstorm.exchange.api.msg.LoadProfileMsgOrBuilder getLoadProfileOrBuilder() {
      if (loadProfileBuilder_ != null) {
        return loadProfileBuilder_.getMessageOrBuilder();
      } else {
        return loadProfile_ == null ?
            io.sandstorm.exchange.api.msg.LoadProfileMsg.getDefaultInstance() : loadProfile_;
      }
    }
    /**
     * <code>.LoadProfileMsg load_profile = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.sandstorm.exchange.api.msg.LoadProfileMsg, io.sandstorm.exchange.api.msg.LoadProfileMsg.Builder, io.sandstorm.exchange.api.msg.LoadProfileMsgOrBuilder> 
        getLoadProfileFieldBuilder() {
      if (loadProfileBuilder_ == null) {
        loadProfileBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.sandstorm.exchange.api.msg.LoadProfileMsg, io.sandstorm.exchange.api.msg.LoadProfileMsg.Builder, io.sandstorm.exchange.api.msg.LoadProfileMsgOrBuilder>(
                getLoadProfile(),
                getParentForChildren(),
                isClean());
        loadProfile_ = null;
      }
      return loadProfileBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TestJobMsg)
  }

  // @@protoc_insertion_point(class_scope:TestJobMsg)
  private static final io.sandstorm.exchange.api.msg.TestJobMsg DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.sandstorm.exchange.api.msg.TestJobMsg();
  }

  public static io.sandstorm.exchange.api.msg.TestJobMsg getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TestJobMsg>
      PARSER = new com.google.protobuf.AbstractParser<TestJobMsg>() {
    public TestJobMsg parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TestJobMsg(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TestJobMsg> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TestJobMsg> getParserForType() {
    return PARSER;
  }

  public io.sandstorm.exchange.api.msg.TestJobMsg getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

