// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package io.sandstorm.exchange.api.msg;

/**
 * Protobuf type {@code UserInjectStepMsg}
 */
public  final class UserInjectStepMsg extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:UserInjectStepMsg)
    UserInjectStepMsgOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserInjectStepMsg.newBuilder() to construct.
  private UserInjectStepMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserInjectStepMsg() {
    totalUsers_ = 0L;
    rateUps_ = 0L;
    duration_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UserInjectStepMsg(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            totalUsers_ = input.readInt64();
            break;
          }
          case 16: {

            rateUps_ = input.readInt64();
            break;
          }
          case 24: {

            duration_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.sandstorm.exchange.api.msg.TestTaskProto.internal_static_UserInjectStepMsg_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.sandstorm.exchange.api.msg.TestTaskProto.internal_static_UserInjectStepMsg_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.sandstorm.exchange.api.msg.UserInjectStepMsg.class, io.sandstorm.exchange.api.msg.UserInjectStepMsg.Builder.class);
  }

  public static final int TOTAL_USERS_FIELD_NUMBER = 1;
  private long totalUsers_;
  /**
   * <code>int64 total_users = 1;</code>
   */
  public long getTotalUsers() {
    return totalUsers_;
  }

  public static final int RATE_UPS_FIELD_NUMBER = 2;
  private long rateUps_;
  /**
   * <code>int64 rate_ups = 2;</code>
   */
  public long getRateUps() {
    return rateUps_;
  }

  public static final int DURATION_FIELD_NUMBER = 3;
  private long duration_;
  /**
   * <code>int64 duration = 3;</code>
   */
  public long getDuration() {
    return duration_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (totalUsers_ != 0L) {
      output.writeInt64(1, totalUsers_);
    }
    if (rateUps_ != 0L) {
      output.writeInt64(2, rateUps_);
    }
    if (duration_ != 0L) {
      output.writeInt64(3, duration_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (totalUsers_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, totalUsers_);
    }
    if (rateUps_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, rateUps_);
    }
    if (duration_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, duration_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.sandstorm.exchange.api.msg.UserInjectStepMsg)) {
      return super.equals(obj);
    }
    io.sandstorm.exchange.api.msg.UserInjectStepMsg other = (io.sandstorm.exchange.api.msg.UserInjectStepMsg) obj;

    boolean result = true;
    result = result && (getTotalUsers()
        == other.getTotalUsers());
    result = result && (getRateUps()
        == other.getRateUps());
    result = result && (getDuration()
        == other.getDuration());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOTAL_USERS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalUsers());
    hash = (37 * hash) + RATE_UPS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRateUps());
    hash = (37 * hash) + DURATION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDuration());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.sandstorm.exchange.api.msg.UserInjectStepMsg parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.sandstorm.exchange.api.msg.UserInjectStepMsg parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.sandstorm.exchange.api.msg.UserInjectStepMsg parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.sandstorm.exchange.api.msg.UserInjectStepMsg parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.sandstorm.exchange.api.msg.UserInjectStepMsg parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.sandstorm.exchange.api.msg.UserInjectStepMsg parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.sandstorm.exchange.api.msg.UserInjectStepMsg parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.sandstorm.exchange.api.msg.UserInjectStepMsg parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.sandstorm.exchange.api.msg.UserInjectStepMsg parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.sandstorm.exchange.api.msg.UserInjectStepMsg parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.sandstorm.exchange.api.msg.UserInjectStepMsg parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.sandstorm.exchange.api.msg.UserInjectStepMsg parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.sandstorm.exchange.api.msg.UserInjectStepMsg prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code UserInjectStepMsg}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:UserInjectStepMsg)
      io.sandstorm.exchange.api.msg.UserInjectStepMsgOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.sandstorm.exchange.api.msg.TestTaskProto.internal_static_UserInjectStepMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.sandstorm.exchange.api.msg.TestTaskProto.internal_static_UserInjectStepMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.sandstorm.exchange.api.msg.UserInjectStepMsg.class, io.sandstorm.exchange.api.msg.UserInjectStepMsg.Builder.class);
    }

    // Construct using io.sandstorm.exchange.api.msg.UserInjectStepMsg.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      totalUsers_ = 0L;

      rateUps_ = 0L;

      duration_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.sandstorm.exchange.api.msg.TestTaskProto.internal_static_UserInjectStepMsg_descriptor;
    }

    public io.sandstorm.exchange.api.msg.UserInjectStepMsg getDefaultInstanceForType() {
      return io.sandstorm.exchange.api.msg.UserInjectStepMsg.getDefaultInstance();
    }

    public io.sandstorm.exchange.api.msg.UserInjectStepMsg build() {
      io.sandstorm.exchange.api.msg.UserInjectStepMsg result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.sandstorm.exchange.api.msg.UserInjectStepMsg buildPartial() {
      io.sandstorm.exchange.api.msg.UserInjectStepMsg result = new io.sandstorm.exchange.api.msg.UserInjectStepMsg(this);
      result.totalUsers_ = totalUsers_;
      result.rateUps_ = rateUps_;
      result.duration_ = duration_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.sandstorm.exchange.api.msg.UserInjectStepMsg) {
        return mergeFrom((io.sandstorm.exchange.api.msg.UserInjectStepMsg)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.sandstorm.exchange.api.msg.UserInjectStepMsg other) {
      if (other == io.sandstorm.exchange.api.msg.UserInjectStepMsg.getDefaultInstance()) return this;
      if (other.getTotalUsers() != 0L) {
        setTotalUsers(other.getTotalUsers());
      }
      if (other.getRateUps() != 0L) {
        setRateUps(other.getRateUps());
      }
      if (other.getDuration() != 0L) {
        setDuration(other.getDuration());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.sandstorm.exchange.api.msg.UserInjectStepMsg parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.sandstorm.exchange.api.msg.UserInjectStepMsg) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long totalUsers_ ;
    /**
     * <code>int64 total_users = 1;</code>
     */
    public long getTotalUsers() {
      return totalUsers_;
    }
    /**
     * <code>int64 total_users = 1;</code>
     */
    public Builder setTotalUsers(long value) {
      
      totalUsers_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 total_users = 1;</code>
     */
    public Builder clearTotalUsers() {
      
      totalUsers_ = 0L;
      onChanged();
      return this;
    }

    private long rateUps_ ;
    /**
     * <code>int64 rate_ups = 2;</code>
     */
    public long getRateUps() {
      return rateUps_;
    }
    /**
     * <code>int64 rate_ups = 2;</code>
     */
    public Builder setRateUps(long value) {
      
      rateUps_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 rate_ups = 2;</code>
     */
    public Builder clearRateUps() {
      
      rateUps_ = 0L;
      onChanged();
      return this;
    }

    private long duration_ ;
    /**
     * <code>int64 duration = 3;</code>
     */
    public long getDuration() {
      return duration_;
    }
    /**
     * <code>int64 duration = 3;</code>
     */
    public Builder setDuration(long value) {
      
      duration_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 duration = 3;</code>
     */
    public Builder clearDuration() {
      
      duration_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:UserInjectStepMsg)
  }

  // @@protoc_insertion_point(class_scope:UserInjectStepMsg)
  private static final io.sandstorm.exchange.api.msg.UserInjectStepMsg DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.sandstorm.exchange.api.msg.UserInjectStepMsg();
  }

  public static io.sandstorm.exchange.api.msg.UserInjectStepMsg getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserInjectStepMsg>
      PARSER = new com.google.protobuf.AbstractParser<UserInjectStepMsg>() {
    public UserInjectStepMsg parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserInjectStepMsg(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UserInjectStepMsg> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserInjectStepMsg> getParserForType() {
    return PARSER;
  }

  public io.sandstorm.exchange.api.msg.UserInjectStepMsg getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

