// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package io.sandstorm.exchange.api.msg;

public interface UserInjectStepMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserInjectStepMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 total_users = 1;</code>
   */
  long getTotalUsers();

  /**
   * <code>int64 rate_ups = 2;</code>
   */
  long getRateUps();

  /**
   * <code>int64 duration = 3;</code>
   */
  long getDuration();
}
