// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package io.sandstorm.exchange.api.msg;

public interface VoidMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VoidMsg)
    com.google.protobuf.MessageOrBuilder {
}
